package diarg.enums;

public enum ResolutionType {
    STANDARD,
    REDUCTIONIST_REFERENCE_INDEPENDENT,
    EXPANSIONIST_REFERENCE_INDEPENDENT,
    REDUCTIONIST_CAUTIOUSLY_MONOTONIC,
    EXPANSIONIST_CAUTIOUSLY_MONOTONIC
}
